### ISSUE TITLE
rake initialize assumes postgresql database is running

### ISSUE THREAD

**Issue by neuronsong** [XingFramework/xing-framework#23]
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"xing_app_dev", "pool"=>5, "host"=>"127.0.0.1"}
could not connect to server: Connection refused
    Is the server running on host "127.0.0.1" and accepting
    TCP/IP connections on port 5432?

It might be more prudent to assume we'll first set up a sqlite database and transition to something like mysql or postgresql later.

**Comment by IdahoEv** [comment]
Thanks for the input.   However, the primary purpose of `rake initialize` is to create and migrate a database, which can't happen unless your RDBMS is running.  

That said, if you don't want to use postgresql, you don't need `rake initialize`.  Pretty much all it does is create an initial set of DB tables for users, create, and migrate your DB - just a five minute convenience for typical projects.  If you'd like to start with SQLite or any other non-PG database, you can edit backend/config/database.yml like any other rails project and use it however you like, and simply skip that particular rake task.  It doesn't do anything magical. 

As for the SQLite option -- it's possible a future version of Xing will support that. Though to be honest, I 
(and the other authors of Xing) have never understood that particular usage pattern. We tend to be heavy users of advanced PostgreSQL column types (HSTORE, JSONB, etc.) and since the cost of leaving a postgresql server running on a workstation is close to zero, we don't really see the advantage of developing against a different database that you'll have to change before production anyway. But YMMV, and if that works for you -- cool.  We will look at supporting it in a future revision.

**Comment by IdahoEv** [comment]
I've added a note to this effect to the super-fast-start page.
