### ISSUE TITLE
rake develop requires redis is running

### ISSUE THREAD

**Issue by neuronsong** [XingFramework/xing-framework#24]
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Dependency Failed: Redis is not running.

**Comment by IdahoEv** [comment]
Redis is listed as a prerequisite for Xing.  The prerequisites checker is designed to help people identify which prerequisites they have not yet set up, rather than have to debug an obscure stack trace later on in the process -- so this is an intentional feature, not a bug.

That said, the prerequisites checker is currently difficult to configure, and so causes a problem for users who want to disable Redis entirely.  We're discussing solutions to that problem right now.

Thanks as always for the input!
